config/routes.rb
Rails.application.routes.draw do
  resources :handles
  root 'handles#index'

end

app/models/handle.rb
class Handle
  include Mongoid::Document
  field :handle_name, type: String

  def client
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["YOUR_CONSUMER_KEY"]
      config.consumer_secret     = ENV["YOUR_CONSUMER_SECRET"]
      config.access_token        = ENV["YOUR_ACCESS_TOKEN"]
      config.access_token_secret = ENV["YOUR_ACCESS_SECRET"]
    end
  end

  def tweets
    self.client
    @client.user_timeline(self.handle_name)
  end

  def characters
    @characters = 0
    @tweets = self.tweets
    @tweets[1..20].each do |tweet|
      @characters += tweet.text.length
    end
    @characters
  end

  def retweets
    @retweets = 0
    @tweets = self.tweets
    @tweets[1..20].each do |tweet|
      @retweets += tweet.retweet_count
    end
    @retweets
  end

  def uris
    @uris = 0
    @tweets = self.tweets
    @tweets[1..20].each do |tweet|
      if tweet.uris?
        @uris += 1
      end
    end
    @uris
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/handles_controller.rb
class HandlesController < ApplicationController
  before_action :set_handle, only: [:show, :edit, :update, :destroy]

  # GET /handles
  # GET /handles.json
  def index
    @handles = Handle.all
  end

  # GET /handles/1
  # GET /handles/1.json
  def show
    @tweets = @handle.tweets
    @tweets_num = @tweets.length
    @retweets = @handle.retweets
    @characters = @handle.characters
    @uris = @handle.uris
    @character_avg = @characters / @tweets_num
  end

  # GET /handles/new
  def new
    @handle = Handle.new
  end

  # GET /handles/1/edit
  def edit
  end

  # POST /handles
  # POST /handles.json
  def create
    @handle = Handle.new(handle_params)

    respond_to do |format|
      if @handle.save
        format.html { redirect_to @handle, notice: 'Handle was successfully created.' }
        format.json { render :show, status: :created, location: @handle }
      else
        format.html { render :new }
        format.json { render json: @handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /handles/1
  # PATCH/PUT /handles/1.json
  def update
    respond_to do |format|
      if @handle.update(handle_params)
        format.html { redirect_to @handle, notice: 'Handle was successfully updated.' }
        format.json { render :show, status: :ok, location: @handle }
      else
        format.html { render :edit }
        format.json { render json: @handle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handles/1
  # DELETE /handles/1.json
  def destroy
    @handle.destroy
    respond_to do |format|
      format.html { redirect_to handles_url, notice: 'Handle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handle
      @handle = Handle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handle_params
      params.require(:handle).permit(:handle_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/handles_helper.rb
module HandlesHelper
end

app/views/handles/_form.html.erb
<%= form_for(@handle) do |f| %>
  <% if @handle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handle.errors.count, "error") %> prohibited this handle from being saved:</h2>

      <ul>
      <% @handle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :handle_name %><br>
    <%= f.text_field :handle_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handles/edit.html.erb
<h1>Editing Handle</h1>

<%= render 'form' %>

<%= link_to 'Show', @handle %> |
<%= link_to 'Back', handles_path %>

app/views/handles/index.html.erb
<div class="panel panel-primary">

<p id="notice"><%= notice %></p>

<h1>Handles</h1>

<table>
  <thead>
    <tr>
      <th>Handle name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @handles.each do |handle| %>
      <tr>
        <td><%= handle.handle_name %></td>
        <td><%= link_to 'Show', handle %></td>
        <td><%= link_to 'Edit', edit_handle_path(handle) %></td>
        <td><%= link_to 'Destroy', handle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Handle', new_handle_path %>

</div>

app/views/handles/new.html.erb
<h1>New Handle</h1>

<%= render 'form' %>

<%= link_to 'Back', handles_path %>

app/views/handles/show.html.erb
<div class="panel panel-primary">
<p id="notice"><%= notice %></p>

  <h2>Handle: <%= @handle.handle_name %></h2>
  </br>
  <strong>Number of Tweets:</strong>
  <%= @tweets_num %>
  </br>
  <strong>Number of Retweets:</strong>
  <%= @retweets %>
  </br>
  <strong>Number of Links:</strong>
  <%= @uris %>
  </br>
  <strong>Average Characters/Tweet:</strong>
  <%= @character_avg %>
  </br>
  </br>

<%= link_to 'Edit', edit_handle_path(@handle) %> |
<%= link_to 'Back', handles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>